### ISSUE TITLE
Jest did not exit one second after the test run has completed

### ISSUE THREAD

**Issue by amoradi** [JordiOrriols/react-visual-regression#8]
I cannot get jest to exit without the `forceExit` flag, please help 😀 

I don't think the library is properly terminating asynchronous operations. I suspect `takeScreenshot` _could_ be the culprit.

<img width="1118" alt="Screen Shot 2020-03-12 at 8 58 29 PM" src="https://user-images.githubusercontent.com/6855005/76580044-d6d63c80-64a4-11ea-9058-03733635bef3.png">

```js
export const takeScreenshot = async (template: string, opts: Options): Promise<string> => {

  if (!browser) {
    browser = await launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
  }

  const page = await browser.newPage();

  const emulateDevice = getDevice(opts.device);

  await page.emulate(emulateDevice);

  await page.setContent(template);

  const image = await page.screenshot();

  await page.close(); // <--- I SEE IT'S CLOSING HERE

  return image;

};
```

```js
// PS I don't think setTimeouts are a proper way of handling this too
beforeEach(() => {
    jest.setTimeout(1000);
});
```

**Comment by JordiOrriols** [comment]
Excuse the late reply!
In fact, we close the page, but not the browser itself. That's why I need the forceExit option.
I have to look at it on the code to improve that part.

Definitely it should close alone.

I need to improve this.
